port = 8888
scripts = "./examples/scripts"
templates = "{{ .PWD }}/examples/templates"
loglevel = "warning"
#tlscert = "./examples/certificate/self-signed.crt"
#tlskey = "./examples/certificate/self-signed.key"

[static]
location = "/assets"
root = "./examples/assets"
spa = "./examples/assets/index.html"

## SQLite
[database]
driver = "sqlite3"
location = "{{ .PWD }}/examples/todo.db"
migrations = "./examples/migrations/sqlite3"

# CRUD routes
[[resource]]
location = "/todos"
method = "GET"
query = "select id, name, description from todos"

[[resource]]
location = "/todos/:id"
method = "GET"
query = "select id, name, description from todos where id = :id"
render = "todo_get.mustache"

[[resource]]
location = "/todos"
method = "POST"
query = "insert into todos(name, description) values(:name, :description)"

[[resource]]
location = "/todos/:id"
method = "PUT"
query = "update todos set name = :name, description = :description where id = :id"

[[resource]]
location = "/todos/:id"
method = "DELETE"
query = "delete from todos where id = :id"


# Erroring routes
[[resource]]
location = "/error/missing_table"
method = "GET"
query = "select id, name, description from missing_table"


[[resource]]
location = "/error/missing_param"
method = "GET"
query = "select id, name, description from missing_table where foo = :bar"
